version: '3'

services:
  jekyllbuild:
    build:
      context: .
      args:
        build_command: "bundle exec jekyll serve --watch --drafts --incremental --config _config-dev.yml"
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000